runtime: python27
api_version: 1
threadsafe: true

#START HANDLERS
handlers:
- url : /static
  static_dir: static
- url: /.*
  script: server.app
#END HANDLERS

#START LIBRARIES
libraries:
- name : ssl
  version: latest
