runtime: python
env: flex
entrypoint: gunicorn -b :$PORT server:app

runtime_config:
        python_version: 3

#START HANDLERS
handlers:
- url : /static
  static_dir: static
- url: /.*
  script: server.app
#END HANDLERS

